### ISSUE TITLE
Webpack not respecting "watchOptions.ignored"

### ISSUE THREAD

**Issue by ChrisSG** [webpack/watchpack#105]
https://github.com/webpack/watchpack/blob/0d5001dff7e60874b9542a5b4bc4ac4b77c7a4bf/lib/DirectoryWatcher.js#L80

**Comment by evilebottnawi** [comment]
@ChrisSG it is alpha version for `webpack@5`, what is problem?

**Comment by ChrisSG** [comment]
Sorry that was a really bad issue description.....  Thank you for replying anyways!

The problem is that I am using WatchIgnorePlugin at the moment to achieve the effect that a directory is ignored when watching. I tried to implement this using the https://webpack.js.org/configuration/watch/#watchoptionsignored option but this did not work. Ther was literally no effect applying those to webpack and the devServer. But wathcing the source code I can't quite explain this at the momement.

Why is there a WatchIgnorePlugin  **and** an option for the same usecase?

**Comment by evilebottnawi** [comment]
And Yes and No, can you create minimum reproducible test repo with description what is work and what is not work as you expected

**Comment by sokra** [comment]
this has been added
