### ISSUE TITLE
Dependencies (chokidar) Security Vulnerabilities 

### ISSUE THREAD

**Issue by michal-ayash** [webpack/watchpack#117]
This package requires old versions of some packages that require 'set-value' with old version (2.0.0) which has vulnerability issue:
1. 'chokidar' 
2. 'anymatch'
3. 'readdirp'

Updating those packages to require the latest versions will resolve the issue.

Thanks,
Michal.

**Comment by evilebottnawi** [comment]
No `Security Vulnerabilities`, it was bug in npm register with version range, also next version doesn't contain chokidar

**Comment by extempl** [comment]
@evilebottnawi Just to clarify, next version which doesn't use chokidar, fixed all those issues noted here: https://github.com/paulmillr/chokidar#user-content-why ?

**Comment by paulmillr** [comment]
@extempl no, of course it doesn't fix cases chokidar handles. The watchpack implementation is naïve.

**Comment by extempl** [comment]
@paulmillr Hm, why then switch from chokidar to naїve? It will result in chokidar use by end-user with a node-sass-chokidar package (or something similar) and its watcher instead if watchpack.

**Comment by paulmillr** [comment]
I don’t know, since i’m not a webpack developer.
