### ISSUE TITLE
Update NPM version release to most recent stable version.

### ISSUE THREAD

**Issue by lf-evergreen** [webpack/watchpack#121]
Currently the version `1.6.0` is published on NPM which contains the `chokidar` package which has vulnerable sub-dependencies (e.g. `braces@2.3.2`, `snapdragon@0.8.2`, etc.). Webpack currently uses this `1.6.0` version of `watchpack` in their `package.json` due to this and is thus installing these vulnerable sub-dependencies.

**Comment by evilebottnawi** [comment]
It is transitive dependencies, we can't update them directly, please update your lock file and dependencies (latest version is not vulnerable). Also latest version of `watchpack` supports only webpack@5

**Comment by lf-evergreen** [comment]
@evilebottnawi I would suggest that you perhaps reread what I wrote. It's not about simply about updating transitive dependencies.
