### ISSUE TITLE
the version of fsevents@1.2.3 install failed on mac

### ISSUE THREAD

**Issue by lscgzwd** [webpack/watchpack#122]
node:v12.6.0

npm WARN deprecated fsevents@1.2.3: Way too old

> fsevents@1.2.3 install /usr/local/lib/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@12.6.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by evilebottnawi** [comment]
Network problem, maybe somebody blocked amazon (maybe provider or government), in Russian it is do Roskomnadzor, unfortunately we can't solve this problem, you can try to use VPN or ask `fsevents` add more mirrors

**Comment by lscgzwd** [comment]
Thanks for you reply, but this maybe not the reason of greatwall, I have downgrade my node to 10.16, then solved.
