### ISSUE TITLE
Directory watching does not work on Windows with forward slashes

### ISSUE THREAD

**Issue by arseneyr** [webpack/watchpack#123]
### Steps to reproduce
Run the following sample in an otherwise empty directory on Windows:
```
const Watchpack = require("watchpack");
const fs = require("fs");

const forwardSlashDir = __dirname.replace(/\\/g, "/");

const wp = new Watchpack();

wp.watch([], [forwardSlashDir]);
wp.on("aggregated", () => console.log("watchpack change!"));
fs.watch(forwardSlashDir, () => console.log("fs change!"));

setTimeout(() => fs.utimesSync(__filename, new Date(), new Date()), 100);
```
#### Expected result
Should print both `watchpack change!` and `fs change!`
#### Actual result
Only prints `fs change!`

### Additional information
Watchpack version: 1.6.0

This seems to be a result of https://github.com/webpack/watchpack/blob/8d839e8b6edb87f9cd8a1ff97028060c4ecc9bee/lib/DirectoryWatcher.js#L259-L260
and is not a problem in 2.x. However, this means that webpack v4 cannot use forward slashes for `addContextDependency()` on Windows. Any chance this can get fixed in 1.x or do we need to wait for webpack v5?

**Comment by sokra** [comment]
wait for webpack 5.
