### ISSUE TITLE
need to update to newer FSEvents for MacOS 15

### ISSUE THREAD

**Issue by mattbishop** [webpack/watchpack#131]
This is for version 1.6.0.
Might be a duplicate for #122

**Comment by evilebottnawi** [comment]
What is problem?

**Comment by mattbishop** [comment]
I can't install webpack because watchpack failed to build due to fsevents on MacOS 15. Below is a log output:

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning Error running install script for optional dependency: "/Users/matt/Projects/Identifiers/identifiers-js/node_modules/fsevents: Command failed.
...
yarn why v1.19.1
[1/4] 🤔  Why do we have the module "fsevents"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "fsevents@1.2.4"
info Reasons this module exists
   - "webpack#watchpack#chokidar" depends on it
   - Hoisted from "webpack#watchpack#chokidar#fsevents"
```

This is an fsevents bug, fixed in version 1.2.9: https://github.com/fsevents/fsevents/pull/274

So, please update watch pack to fsevents 1.2.9.

Thanks!

**Comment by evilebottnawi** [comment]
Just update own deps/lock file

**Comment by mattbishop** [comment]
Yes, but I was filing this so you can help your other users avoid this in the future. Being part of a well-used project like webpack has some heightened responsibilities, like keeping your dependencies up-to-date.

**Comment by evilebottnawi** [comment]
@mattbishop so we use `^` for packages in `package.json`, each fresh installation will get new versions, we don't want do release on each patch version of dependencies and transitive dependencies, so update you lock file, you can setup `renovate` or other dependencies bots to keep lock file up to date
