### ISSUE TITLE
Update Chokidar to v3 for watchpack@1.x.x

### ISSUE THREAD

**Issue by guidobouman** [webpack/watchpack#137]
`watchpack@1.x` causes `chokidar@2.1.8` + `fsevents@1.2.11` to be installed. Which breaks on Windows with `npm ci` installs.

Using `chokidar@3.x` in the `v1.x` branch allows `fsvents@2.x` to be installed, which allows ci installs on Windows to succeed again. With every package update, I now have to manually roll back the `fsevents` update. Yes, I've brought this up with the package owner, but he's also in a position where `fsevents@1.x` is unmaintainable. This package would benefit a lot from the update in the current `v1.x` branch. Because current installs of webpack / watchpack are starting to fail more & more.

**Comment by evilebottnawi** [comment]
We can't do it because it is breaking change, what is broken? Can you create reproducible test repo?

**Comment by guidobouman** [comment]
Would that directly cause a breaking change in the watchpack? I don't see the need for a breaking change in watchpack to update a dependency. Or do I see this wrong?

**Comment by evilebottnawi** [comment]
@guidobouman webpack@4 support node@6, `chokidar@3.x` require node@8

**Comment by guidobouman** [comment]
Hmm... You mean Node 6, which has been EOL since april 30, 2019? I get that you want to respect old versions, even if they are EOL. But should a widespread package like webpack not also push ahead the platform as a whole? 


Google is decommissioning Node 6 cloud functions on April 22, 2020. And Amazon has deprecated Node 6 for Lambda functions on August 12, 2019:
https://aws.amazon.com/blogs/developer/node-js-6-is-approaching-end-of-life-upgrade-your-aws-lambda-functions-to-the-node-js-10-lts/

**Comment by evilebottnawi** [comment]
@guidobouman yes, but it will be in webpack@5, we can't break support for node@6 projects

**Comment by guidobouman** [comment]
Fair point. Sorry for pushing beyond reasonable semver logic.

**Comment by guidobouman** [comment]
Oh, forgot the second part about a reproducible demo, see https://github.com/npm/cli/issues/658.

1. Run npm init in a new directory on a windows machine
1. Install a package with an optional dependency on fsevents, like webpack: npm i webpack
1. Notice a package-lock.json being created with an optional dependency on fsevents@1.2.11
1. Run npm ci, and see the install failing because fsevents in being downloaded, installed, and node-gyp is being executed as a result.


Might need to remove `node_modules` in between 3& 4.
