### ISSUE TITLE
DirectoryWatcher doesn't detect changes

### ISSUE THREAD

**Issue by zzacharo** [webpack/watchpack#141]
Hello,

I am using watchpack version 1.6 along with webpack 4. Integrating the livereload plugin in my webpack config, files are being watched and rebuilt correctly in linux environment but when I am testing it in `OSX` then changed files don't trigger any rebuilt. 

After digging a bit into the code I ended up changing the options that are being passed down to `chokidar` [here](https://github.com/webpack/watchpack/blob/v1.6.0/lib/DirectoryWatcher.js#L57) and specifically increasing the `depth` option from `0` -> `1` did the trick. 

Is this a known issue with the `1.6` version? Will this be fixed in watchpack 2?

Thanks for helping :)

**Comment by alexander-akait** [comment]
Sorry for that and no answer, a lot of time has passed, if it is still make sense for you feel free to ping me or reopen, sorry again
