### ISSUE TITLE
Watch does not recover from (forced) build error

### ISSUE THREAD

**Issue by istr** [webpack/watchpack#15]
I try to use watcher to rebuild automatically but fail the builds when jscs or jshint on a source file fails.
This works only once. After the first rebuild that is triggered through changing a watched file, any further update on any of the watched files will be ignored. It seems that watcher does not recover from the build error enforced by ```failOnHint: true```. If I turn off ```failOnHint``` the rebuild process works as expected (issues an error, but builds with errors), but this is not what I intend to do.

This is the relevant part of my ```webpack.config.js```

```javascript
module.exports = {
    target: 'web',
    cache: true,
    watch: true,
    jscs: {
        // enforce jscs-passing builds only
        emitErrors: true,
        failOnHint: true,
        // pass down these options to jscs
        preset: 'google',
        requireCamelCaseOrUpperCaseIdentifiers: 'ignoreProperties',
        validateIndentation: null
    },
    jshint: {
        // enforce jshint-passing builds only
        emitErrors: true,
        failOnHint: true,
        // pass down these options to jshint
        browser: true,
        browserify: true,
        bitwise: true,
        ....
```

Anybody having this issue, too? Or any hint on how to fix this? Using polling mode does not work, either.

**Comment by istr** [comment]
I am not sure if this issue belongs here or to the [main webpack repo](https://github.com/webpack/webpack). Please advise. Thanks.

**Comment by sokra** [comment]
Not related to watchpack.
