### ISSUE TITLE
Incompatible with Node 14

### ISSUE THREAD

**Issue by csvan** [webpack/watchpack#156]
Installing webpack 4 on a Nodejs 14.1 system (latest stable as of writing this) yields:

`webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`

Even though I am not sure I see any immediate issues, this should be addressed ASAP. Further, Chokidar3 is much, much smaller than Chokidar2 and would reduce the footprint of webpack as a whole.

**Comment by jaylinski** [comment]
Wasn't this fixed in https://github.com/webpack/watchpack/pull/153?

**Comment by evilebottnawi** [comment]
Yes, fixed

**Comment by evilebottnawi** [comment]
You need to install latest `chokidar` manually for webpack@4, just run `npm i -D chokidar`

**Comment by Luxcium** [comment]
I have those warnings:

```log
 npm install webpack@4                  

npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"15.1.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

# [ ... ]

```

I can run «npm i -D chokidar» what if I later, want to use, webpack@{ latest | next }
