### ISSUE TITLE
Does not detect minor changes to the file (added/removed whitespace, semicolon)

### ISSUE THREAD

**Issue by gajus** [webpack/watchpack#16]
Subject:

```js
let foo

console.log('abc', foo);
```

I am using:

* webpack
* eslint-loader

I am running webpack using `webpack --watch --progress`.

The following output is generated:

```
ERROR in ./foo.js

/foo.js
  1:7  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```

So far so good.

I edit the subject file:

```js
let foo;

console.log('abc', foo);
```

`webpack` CLI `--progress` indicates that package is re-built. **However, error output remains.**

I edit the subject file (edit the string):

```js
let foo;

console.log('def', foo);
```

`webpack` CLI `--progress` indicates that package is re-built. The error disappears.

Therefore, it appears that adding/removing a semicolon does not trigger loaders.

**Comment by gajus** [comment]
`webpack.OldWatchingPlugin()` does not suffer from the same behaviour.

**Comment by gajus** [comment]
In addition to using the `OldWatchPlugin`, it is worth considering using `nodemon`, http://stackoverflow.com/a/33109171/368691.

**Comment by sokra** [comment]
watchpack doesn't read the file. If this is still an issue report it to webpack.
