### ISSUE TITLE
Webpack stops watching subdirectories when the last file in a directory is no longer referenced

### ISSUE THREAD

**Issue by xandris** [webpack/watchpack#162]
Here's a minimal test case:

https://github.com/xandris/webpack-intermediate-dir-watch-bug

The project is set up like this:

```
src
├── entry
│   └── index.js
└── utils.js
```

The entrypoint is `src/entry/index.js`, which imports `src/utils.js`. If during a `--watch` session, `src/entry/index.js` no longer imports `src/utils.js`, I think the refcount on `src/` goes to zero, which closes its watcher and the watcher on `src/entry`. Further edits to `src/entry/index.js` aren't detected.

I think what should happen instead is that the refcount on `src/` should take into account its child watcher, `src/entry`. Apologies if my analysis is off base.

**Comment by alexander-akait** [comment]
Sorry for that and no answer, a lot of time has passed, if it is still make sense for you feel free to ping me or reopen, sorry again
