### ISSUE TITLE
how to mandatory use chokidar2 ?

### ISSUE THREAD

**Issue by DiamondYuan** [webpack/watchpack#163]
```
└── myproject
    ├── chokidar@2
    └── webpack@latest
        └── watchpack@1.x
            ├── chokidar@3     How to delete it ?
            └── watchpack-chokidar2
                └── chokidar@2
```

I use webpack in electron@3 . and electron@3 not support chokider3.
If i use webpack, npm will automatic insall watchpack@1.7.2 and chokider3.

Is there a way to make watchpack use only chokidar2?

**Comment by evilebottnawi** [comment]
We don't install `chokidar@3` by default, you should manually add `chokidar` to `package.json` if you need latest version, bu default we install only `chokidar@2`, check you dependencies again
