### ISSUE TITLE
Does't watch changes with a large codebase

### ISSUE THREAD

**Issue by WaveString** [webpack/watchpack#174]
I am migrating a project from webpack 4 to webpack 5.
The project contains a large code base, most of the files are contained in node_modules. After building in dev mode, webpack does not rebuild to file changes, it does not even give an error. 
After a series of experiments on disabling package imports, at some point the watch mode starts working, because there is less code in build.

When `poll:true`, watch mode starts working, but rebuild takes extremely long time(about 40 seconds)

I can try set `ulimit -n` and `maxfiles` to max values, but that didn't help.

version: 2.0.0-beta.14
os: macOS 10.15.4

**Comment by evilebottnawi** [comment]
@WaveString What is webpack version? Can you provide more information? Maybe even screenshots/videos/reproducible test repo/something else

**Comment by WaveString** [comment]
Webpack version: `5.0.0-beta.28`.

I can try creating a repo with empty files, but not sure what will reproduce this behavior.

**Comment by evilebottnawi** [comment]
@WaveString screenshots/videos?

**Comment by WaveString** [comment]
With full code base, watch mode is ignored(already built) [full-codebase](https://drive.google.com/file/d/11bURoR4xy8IvgHPA9clZFDSXCLm1RxPG/view)
With half of the import packages removed, watch mode works [half-codebase](https://drive.google.com/file/d/17NZ7i0TNXwlyGf6qXxL_Y31EuURH68hf/view)

**Comment by evilebottnawi** [comment]
Very weird, can you try it without webpack-dev-server (just `--watch`)? Can you provide list of plugins (or try to disable them step by step)?

**Comment by WaveString** [comment]
I disabled all plugins, build without `webpack-dev-server`, but it not helps.

I am debugged watchpack a little and found that if the code does not fall into this condition, then the watch mode does not work.
```
// Fast case when we are not reaching the limit
	if (!SUPPORTS_RECURSIVE_WATCHING || watcherLimit - watcherCount >= map.size) {
		// Create watchers for all entries in the map
		for (const [filePath, entry] of map) {
			const w = createDirectWatcher(filePath);
			if (Array.isArray(entry)) {
				for (const item of entry) w.add(item);
			} else {
				w.add(entry);
			}
		}
		return;
	}
```

When built with full codebase `map.size=2698` and `watcherLimit=2000`, when built half codebase `map.size=1262`.

**Comment by evilebottnawi** [comment]
Can you try to do it `truly` and check?

**Comment by WaveString** [comment]
I restored all webpack settings, and got these parameters: `map.size=9248`, `watcherLimit=2000`
When I set it truly, I caught a lot of errors `Watchpack Error (watcher): Error: EMFILE: too many open files, watch`

**Comment by evilebottnawi** [comment]
@WaveString Can you provide `watcherLimit`, `watcherCount` and `map.size` values?

**Comment by WaveString** [comment]
Yep, `map.size=9248`, `watcherLimit=2000`, `watcherCount=0`.
watcherCount always equals zero.

**Comment by sokra** [comment]
That seem to be an interesting case. It's not unlikely that there are still bugs in the recursive watching code (it's very new). Without access to a repro it's very difficult to find the bug for us, but maybe you can debug and find the bug yourself. Here is more information about the topic.

* on MacOS there is a hard watcher limit of 4096. We didn't figure out how to change it, so there seem to be no workaround here.
* But MacOS support recursive watchers, which watch a whole directory tree. By default watchpack watches each directory on its own to prevent overwatching.
* So once the watcherLimit (`WATCHPACK_WATCHER_LIMIT` env variable) is reached, watchpack start to use recursive watchers instead. This works as following:
* There are 2 kinds of watchers: Direct watchers and recursive watchers.
* All watcher requests are batched. When the existing watchers + requests <= limit: Direct watchers are created
* When existing watchers + request > limit: watchers creates a new watch plan with recursive and direct watchers that is 10% below the limit.

This code snippet takes care of planning and creating the watchers in the complex case:

https://github.com/webpack/watchpack/blob/ce3b818757845e37e2c0203b8f7d3b3d6c5995f7/lib/watchEventSource.js#L230-L266

This module takes care of deciding watch directories are recursively watched: https://github.com/webpack/watchpack/blob/master/lib/reducePlan.js

Maybe you start logging out which directories are recursively watched. Are only changes to recursive watchers affected, or is this a general problem?

Maybe there is a bug in reducePlan and some directories get lost during planning in some edge cases? Is the plan correct? Is your directory watched at all?

**Comment by WaveString** [comment]
From what I found:

- Recursive watchers do not work correctly in this case, when codebase is small, compilation uses direct watchers.
- When using recursive watchers, the change event is dispatched not only for the project directories, but in general for the entire file system, such as `/`, `/ Users`,` / Users/evgeny`, `/ Users/evgeny/Projects` are recursively scanned. I get a lot of unnecessary messages about file changes from other apps, but maybe this is not such a big problem.
- In watch function I get strange file paths, with duplicate project paths like `Users/evgeny/Projects/myProject/Users/evgeny/Projects/myProject/`
https://github.com/webpack/watchpack/blob/ce3b818757845e37e2c0203b8f7d3b3d6c5995f7/lib/watchEventSource.js#L269
- The error in recursive watchers is that it does not find the correct watcher, it is always undefined, I tried to fix it, but it works strange, only 1 rebuild and very slow.
https://github.com/webpack/watchpack/blob/ce3b818757845e37e2c0203b8f7d3b3d6c5995f7/lib/watchEventSource.js#L125
I think `subpath ` should be replaced with `filepath`, because, the search for the watcher occurs by directory, not `subpath`

**Comment by evilebottnawi** [comment]
> In watch function I get strange file paths, with duplicate project paths like `Users/evgeny/Projects/myProject/Users/evgeny/Projects/myProject/`

Interesting, very interesting, maybe some plugin do it, what is plugins do you use?

**Comment by WaveString** [comment]
> Interesting, very interesting, maybe some plugin do it, what is plugins do you use?

For this case, I created a test repository, these paths are reproduced https://github.com/WaveString/webpack-5-example

<img width="992" alt="Screenshot at Aug 27 15-28-40" src="https://user-images.githubusercontent.com/7781512/91417442-fdcdd280-e87a-11ea-85f7-cfdc878c2bbc.png">

**Comment by sokra** [comment]
I wasn't able to reproduce the weird paths in your repro. Probably it's a MacOS only issue...

But I found some bugs in the recursive watching code path and fixed them in https://github.com/webpack/watchpack/releases/tag/v2.0.0-beta.15
I can't tell for sure that it fixes your problems, but maybe you can try this release and verify it.
There is also a logging mode enabled with `WATCHPACK_RECURSIVE_WATCHER_LOGGING=1` env var, which tells you what the recursive watchers do...

**Comment by WaveString** [comment]
Thanks, I checked watch mode, it works now! Entire file system is now also not watching as far as I can see.

Now rebuild takes 1 minute. But it seems this is another story.

**Comment by sokra** [comment]
> But it seems this is another story.

Try `--progress --profile` for a fast profiling...

**Comment by evilebottnawi** [comment]
@WaveString How long it was for webpack@4?

**Comment by sokra** [comment]
@WaveString If you have more info, feel free to open an issue in webpack/webpack. I'll close this issue.
