### ISSUE TITLE
Just wonder why app dies on missing 'optionalDependencies'

### ISSUE THREAD

**Issue by chubun** [webpack/watchpack#193]
My app dies with the following error message:

myapp\node_modules\watchpack\lib\chokidar.js:17
throw new Error(
      ^
Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
 
From package.json:

 "optionalDependencies": {
    "chokidar": "^3.4.1",
    "watchpack-chokidar2": "^2.0.1"
  },

I thought 'optional' means 'can work without'?

**Comment by alexander-akait** [comment]
You don't have `chokidar`, please run `npm ls chokidar`/`yarn why chokidar`

**Comment by chubun** [comment]
My question is, is it supposed to happen that something marked as 'optional' can prevent an app from running?  I'm an old school C/C++ programmer.  All these template/configuration based stuff are quite a 'culture shock' to me.

**Comment by alexander-akait** [comment]
In theory no - https://classic.yarnpkg.com/en/docs/dependency-types/#toc-optionaldependencies

But i real world based on how programmer write the code :smile:

**Comment by chubun** [comment]
Good to know.  Thanks for the insight.
