### ISSUE TITLE
Try-catch-block in all *Watcher constructors will hide the legit error

### ISSUE THREAD

**Issue by wood1986** [webpack/watchpack#201]
https://github.com/webpack/watchpack/blob/c651129195d84cc80e547a45be38861b5bbada1a/lib/watchEventSource.js#L42-L61

what if line 43 watch an invalid path? Currently, it is hiding a legit error of this bug in enhance-resolve https://github.com/webpack/enhanced-resolve/issues/311

Here is the reproducible repo https://github.com/wood1986/rootplugin-bug
1. yarn
2. yarn start

If you do not patch fs, you wont be able to see the issue.

**Comment by wood1986** [comment]
If I remove the try catch block, I think it will break all the people. I can do this `watcher.on && watcher.on()`. But does it make sense? And I think we should have a warning message

**Comment by alexander-akait** [comment]
It will be very spammy

**Comment by alexander-akait** [comment]
But paths are expected, I describe example
