### ISSUE TITLE
Push latest release to npm

### ISSUE THREAD

**Issue by meelash** [webpack/watchpack#214]
Could we have the npm package updated, please? It is still on 2.0.1 and there are dependencies that require 2.3.1 so installs fail.

(Obviously workaround is to add directly from the repo, but it will be more seamless for users to have npm updated.)

**Comment by alexander-akait** [comment]
@meelash can you check your register, latest version is published

**Comment by FBNitro** [comment]
I am also still seeing the latest as 2.0.1, as is npmjs.

https://www.npmjs.com/package/watchpack-chokidar2

> Current Tags
 Version Downloads (Last 7 Days)
Tag [2.0.1](https://www.npmjs.com/package/watchpack-chokidar2/v/2.0.1) 7,610,496
latest

**Comment by meelash** [comment]
Thanks. Sorry for missing the Mar 15 comment.
