### ISSUE TITLE
Storybook local build issue on macOS - Watchpack Error (watcher): Error: EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by Ganesh-ui-dotcom** [webpack/watchpack#244]
We are getting following error while local build of storybook on macOS machines.
`Watchpack Error (watcher): Error: EMFILE: too many open files, watch`

Versions: -
Storybook - 8.2.8
Webpack - 5.88.2

Interestingly this issue is not observed on other platforms.

Increasing the open file size does not seem to work as its already set to high.

Following configuration does work but need a permanent fix for this issue.
```
watchOptions: {
     poll: 1000,
}
```

**Comment by alexander-akait** [comment]
Here guide how to solve it - https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files, we can't fix it here
