### ISSUE TITLE
watchpack doesn't emit "remove" event on file remove

### ISSUE THREAD

**Issue by narqo** [webpack/watchpack#27]
It seems that `Watchpack` doesn't listen to any file events from underlying watchers except `change` (see [the code](https://github.com/webpack/watchpack/blob/946a4b018e3b811db255357bc7bcda33c601155c/lib/watchpack.js#L94-L97)). 
It might be handy to have `remove` event as well. Relates to webpack/webpack#1533.

/cc @dfilatov @veged

**Comment by SpaceK33z** [comment]
Closing this since #37 was merged. A new version will be released soon.
