### ISSUE TITLE
watchpack doesn't emit events on nested directories remove

### ISSUE THREAD

**Issue by narqo** [webpack/watchpack#28]
Look like watchpack only listens to changes in top-level dirs from the list passed to `watch()` method. No events from nested directories (e.g. remove, rename, etc) are emitted.

**Comment by karneaud** [comment]
+1

**Comment by evilebottnawi** [comment]
@narqo @veged @karneaud Sorry for delay! Problem still exists? If yes can you create minimum reproducible test repo?

**Comment by RustyRaptor** [comment]
I believe I am having this issue as well but I am not sure if it's the same thing. I have my app.js in ./src/ and I have the rest of my components in ./src/components and when I make changes to those components webpack --watch and the dev server won't recompile. Is this what's happening here?

**Comment by sokra** [comment]
I guess the problem is solved

**Comment by a-m-dev** [comment]
still not resolved , having the same issue
