### ISSUE TITLE
onWatcherError swallows

### ISSUE THREAD

**Issue by minedeljkovic** [webpack/watchpack#29]
Is there a reason for swallowing errors in:
https://github.com/webpack/watchpack/blob/2ba154a81dd151a0f1857ea5395954a7d9891ed7/lib/DirectoryWatcher.js#L264

I just spent couple of hours tracing just to find error like [this](https://github.com/paulmillr/chokidar/issues/255) swallowed :)

**Comment by evilebottnawi** [comment]
@minedeljkovic problem still exists?

**Comment by minedeljkovic** [comment]
Frankly, I can't remember in what context I had this issue so long ago :)
