### ISSUE TITLE
Passing options to chokidar (watching broken over NFS)

### ISSUE THREAD

**Issue by wbinnssmith** [webpack/watchpack#3]
Similar to [watchify#162](https://github.com/substack/watchify/issues/162), I believe it would be best to allow the user to pass chokidar options to watchpack. Without the ability to opt into `usePolling`, webpack's watching is unresponsive when watching files mounted over NFS (which can't implement inotify/fsevents or the like). I imagine that adjusting the poll frequency would be great too. If this happens we'd have to implement the passing through webpack as well.

I tried the old watcher plugin and it does not seem to fix this issue either, but let me know otherwise.

**Comment by zertosh** [comment]
@sokra I think it'd be helpful to the community if we (watchify and watchpack) implemented the same interface for passing options to chokidar. My guess is that with everyone moving apps into containers, this NFS issue is going to keep popping up. I'd appreciate your input on https://github.com/substack/watchify/issues/162

**Comment by SevereOverfl0w** [comment]
substack/watchify#162 is now closed. Will something similar be used in webpack?

**Comment by SpaceK33z** [comment]
Is it possible to use the `poll` configuration option from the command line? E.g. `webpack --watch --poll`?
