### ISSUE TITLE
webpack watch doesn't work, i run npm test, fails~ what's going on? node:6.6.0,npm:3.10.3,webpack:1.13.2

### ISSUE THREAD

**Issue by DanielWLam** [webpack/watchpack#30]
> watchpack@0.2.9 pretest /home/duoyi/learning/webpackEs6/node_modules/watchpack
> npm run lint
> 
> watchpack@0.2.9 lint /home/duoyi/learning/webpackEs6/node_modules/watchpack
> eslint lib
> 
> watchpack@0.2.9 test /home/duoyi/learning/webpackEs6/node_modules/watchpack
> mocha

  DirectoryWatcher
    1) should detect a file creation
DirectoryWatcher (/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures) was not closed.
    2) should detect a file change
DirectoryWatcher (/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures) was not closed.
    ✓ should not detect a file change in initial scan (202ms)
    ✓ should detect a file change in initial scan with start date (2005ms)
    ✓ should not detect a file change in initial scan without start date (202ms)
    3) should detect multiple file changes (slow)
DirectoryWatcher (/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures) was not closed.
    4) should detect multiple file changes (fast)
DirectoryWatcher (/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures) was not closed.

  Watchpack
    5) should watch a single file
    6) "after each" hook

  3 passing (58s)
  6 failing

  1) DirectoryWatcher should detect a file creation:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

  2) DirectoryWatcher should detect a file change:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

  3) DirectoryWatcher should detect multiple file changes (slow):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

  4) DirectoryWatcher should detect multiple file changes (fast):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

  5) Watchpack should watch a single file:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

  6) Watchpack "after each" hook:

```
  Uncaught AssertionError: expected [
```

  '/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures {}'
] to equal [](at length, A has 1 and B has 0)
      + expected - actual

```
  -[
  -  "/home/duoyi/learning/webpackEs6/node_modules/watchpack/test/fixtures {}"
  -]
  +[]

  at Assertion.fail (node_modules/should/lib/assertion.js:183:17)
  at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:68:17)
  at TestHelper.<anonymous> (test/helpers/TestHelper.js:31:59)
  at Timeout._onTimeout (test/helpers/TestHelper.js:59:3)
```

npm ERR! Test failed.  See above for more details.

**Comment by DanielWLam** [comment]
Seems that if i install the 1.12.11 version of webpack , watch is fine.

**Comment by SpaceK33z** [comment]
Closing because it seems to be fixed with the new version.
