### ISSUE TITLE
Watching doesn't work if parent directory contains special characters

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/watchpack#42]
Easiest way to reproduce this is by running the [webpack tutorial](https://webpack.github.io/docs/tutorials/getting-started/) from a directory that contains parentheses in the name.

This is an issue in chokidar (see https://github.com/paulmillr/chokidar/issues/533). There is a [PR open](https://github.com/paulmillr/chokidar/pull/535) to fix it.

This will also be fixed if we move to another watching library, which https://github.com/webpack/watchpack/pull/41 intends to do.

For more info:

- https://github.com/webpack/webpack/issues/2258
- https://github.com/webpack/webpack/issues/2753

**Comment by marcoqu** [comment]
Hi, any news on this?
Is watchpack going to move to sane or are we waiting a patch for chokidar?
Just asking because I'm stuck on a Dropbox Business folder, and there's no way to make it work...
Thanks

**Comment by gbmeireles** [comment]
@marcoqu I manage to get it working by making a link to a folder without any especial characters.
On windows on an admin prompt:
mklink /J "C:\Projects" "C:\Dropbox (Business)\Projects"

**Comment by shshaw** [comment]
@gbmeireles In this case, `C:\Projects` is the link and `C:\Dropbox (Business)\Projects` is where the actual files reside?

**Comment by gbmeireles** [comment]
@shshaw Yes, that`s right.

**Comment by gbmeireles** [comment]
@shshaw @marcoqu I spoke too soon. I think I was looking into some other project path. The symlink approach is not working. Sorry.

**Comment by marcoqu** [comment]
@gbmeireles @shshaw The issue with dropbox businness and watchpack is that watchpack does not work with folders with brackets or with symlinks, and dropbox also doens't sync symlinks. So that won't fix it.

The hack that made it work for me is manually replacing is-glob used by chokidar with the latest version (3.1.0?). That actually worked. See also: paulmillr/chokidar#533

**Comment by Jorenm** [comment]
Here's a copy of the shrinkwrap I used to fix it:

```
{
  "dependencies": {
    "chokidar": {
      "version": "1.6.1",
      "from": "chokidar@1.6.1",
      "dependencies": {
        "is-glob": {
          "version": "3.1.0",
          "from": "is-glob@2.0.1"
        }
      }
    }
  }
}
```

**Comment by syed834** [comment]
**_

- [ ] ![Uploading image (1).jpg…]()

_**
