### ISSUE TITLE
Watch Mode stops functioning if emitted file is busy or locked

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/watchpack#44]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When in watch mode, if a file is busy when attempting to emit to it, watch stops functioning. The following error is appropriately logged: 
```
Error: EBUSY: resource busy or locked, open '..\js\bundle.js'
    at Error (native)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
run webpack --watch
save a watched file
output to a file which is currently being used by another process

**What is the expected behavior?**
An error is logged to the console but watch mode continues to function. This is the behavior of Grunt and Gulp watchers.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
A valid reason why a file could be momentarily busy is if it is being synced to a server directory.

--

Here are the details of my setup:
* webpack version: 2.1.0-beta.25
* node version: 6.9.1
* os: windows 10
* browser: chrome 55

--

**Moved from https://github.com/webpack/webpack/issues/3523**

**Comment by mika76** [comment]
ping 🏓 

This is such an irritating little issue, couldn't someone please take it up? 🙏

**Comment by hotwer** [comment]
I agree, sometimes webpack takes a while to restart, having the watch restart by itself is important.

**Comment by tbondon** [comment]
I've had this problem for 2 weeks and finally found a solution, it may not be the case for everyone but I use OneDrive to save my files and coincidentally when i checked right after having the issue, OneDrive was uploading the damn file. So I just stopped OneDrive :P

**Comment by sokra** [comment]
old issue, create a new issue if this is still an issue
