### ISSUE TITLE
watchpack watch not triggering when symlinked node_module files are modified when using webpack 'symlinks: true'

### ISSUE THREAD

**Issue by txinfo** [webpack/watchpack#61]
In a regular webpack project, a symlinked module in node_modules is watched for changes correctly (as long as the module in question is referenced).

However, if using 'symlinks:true' in webpack to resolve symlinks to their full path (e.g. when using --preserve-symlinks behaviour in angular-cli), it does not seem to watch for changes anymore.

I have tracked this behaviour down to the 'followSymlinks' option of DirectoryWatcher in watchpack (https://github.com/webpack/watchpack/blob/master/lib/DirectoryWatcher.js). The followSymlinks option is always set to false which causes an issue with file watching when webpack is set to resolve symlinks. If it is manually set to true in this scenario, the watching works. Ideally this option would be configurable.

**Comment by jukibom** [comment]
anyone looking for a horrifying stopgap waiting for this to be fixed, add 
```"postinstall": "sed -i 's/followSymlinks: false/followSymlinks: true/g' node_modules/watchpack/lib/DirectoryWatcher.js"```
to package.json. Probably don't commit it into your repo though ;P

**Comment by needo2** [comment]
Experiencing this with 'symlinks: false'

**Comment by LaKing** [comment]
Finally I found this. Fix from @jukibom works!

**Comment by floribon** [comment]
I'm also having this problem when I symlink a folder in my node_modules and use `symlinks: false`.

@jukibom workaround works for now. Thanks!

**Comment by bkniffler** [comment]
Just in case @jukibom command doesn't work on your platform, you can install `replace` package from npm globally or locally and add this in `postinstall`.

```bash
replace 'followSymlinks: false' 'followSymlinks: true' node_modules/watchpack/lib/DirectoryWatcher.js
```

Its 100% analog to @jukibom solution, so all credits to him!

**Comment by raf64flo** [comment]
I fear @jukibom's workaround is not working anymore since commit 805b66502e43be4b1892d2cc0b160e4c53e32e38 which removes dependency to chokidar and symlinks configuration..

@sokra any chance to have a symlink option with the new native watcher, before v2.0.0 goes GA?

**Comment by cristian-spiescu** [comment]
1) @raf64flo, in my case @jukibom's fix still works. At time of writing I use webpack 4.41.0.
2) I built upon @jukibom's suggestion in order to perform the modification at runtime, via monkeypatching, and have a "less temporary" temporary code:

```js
var Module = require('module');
var originalRequire = Module.prototype.require;

Module.prototype.require = function () {
  const original = originalRequire.apply(this, arguments);
  if ("chokidar" === arguments[0]) {
    var originalWatch = original.watch;
    original.watch = function () {
      const options = arguments[1];
      if (options) {
        options.followSymlinks = true;
      }

      return originalWatch.apply(this, arguments);
    }
  }
  return original;
};
```
This piece of code should execute early, in the start script which ultimately launches webpack. In my case, I use https://github.com/gsoft-inc/craco, so I put it in `craco.config.js` which is getting called quite early.
