### ISSUE TITLE
Improve documentation regarding CSPs

### ISSUE THREAD

**Issue by frontendphil** [webpack/watchpack#75]
I'm creating this issue as a result of https://github.com/webpack/webpack.js.org/pull/1833#issuecomment-376500475. The current docs regarding how the `__webpack_nonce__` should be used are still lacking necessary information. 

- Where to put `__webpack_nonce__`
  - Is it a build-time setting
  - How to inject if it is not a build-time setting? (does setting `window.__webpack_nonce__` work?)
- Are there any hooks?

**Comment by evilebottnawi** [comment]
Issue not related to `watchpack`
