### ISSUE TITLE
failing unit tests on Node.js 4

### ISSUE THREAD

**Issue by DanielRuf** [webpack/watchpack#79]
I'll probably investigate this but these should not fail. Not yet sure if this is due to the (dev)dependencies or other changes.

**Comment by evilebottnawi** [comment]
looks like randomly fail

**Comment by DanielRuf** [comment]
> Node 4 is EOL and should probably be dropped

I agree. And 10 should be added.

**Comment by evilebottnawi** [comment]
@DanielRuf Feel free to send PR :+1:
