### ISSUE TITLE
[Feature request] Config for only watching some of the events

### ISSUE THREAD

**Issue by meteorlxy** [webpack/watchpack#82]
Currently, we are watching all the events:
https://github.com/webpack/watchpack/blob/8d839e8b6edb87f9cd8a1ff97028060c4ecc9bee/lib/DirectoryWatcher.js#L67-L72

In our case (https://github.com/vuejs/vuepress/issues/351), we only want webpack to watch `change` events, and other events will be handled by ourselves.

**Comment by evilebottnawi** [comment]
@meteorlxy PR welcome :+1:
