### ISSUE TITLE
Please update chokidar

### ISSUE THREAD

**Issue by DamienCassou** [webpack/watchpack#87]
chokidar 2.0.4 includes a [fix to work with nodejs 10](https://github.com/paulmillr/chokidar/commit/11aea72ad7c65216a0f767142ce57151c7b3d0c1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Can you please update?

**Comment by evilebottnawi** [comment]
@DamienCassou Please update you deps and `lock` file
