### ISSUE TITLE
Automatic test itself seems to have problems

### ISSUE THREAD

**Issue by yuchonghua** [webpack/watchpack#98]
Automatic test itself seems to have problems

see: https://github.com/webpack/watchpack/issues/14

see: https://github.com/webpack/watchpack/pull/96#issuecomment-463068962
> I found that when I closed pr and reopened pr, these automatic tests have randomness on travis-ci.org. What is the reason?
It should not be a problem I changed.

---
see: https://travis-ci.org/webpack/watchpack/builds/492544114?utm_source=github_status&utm_medium=notification
![image](https://user-images.githubusercontent.com/17898715/52690639-4f648400-2f99-11e9-83ce-de8105df7d23.png)

---
see: https://travis-ci.org/webpack/watchpack/builds/492541145?utm_source=github_status&utm_medium=notification
![image](https://user-images.githubusercontent.com/17898715/52690678-6b682580-2f99-11e9-9c8f-e10e620008f9.png)

**Comment by HadiChen** [comment]
What is the cause of this, is it a problem with Travis CI?

**Comment by evilebottnawi** [comment]
Looks like concurrency in test sometimes, need fix it, feel free to investigate and send a PR

**Comment by sokra** [comment]
This seem to be fixed, everything is more stable now and CI has no random failure on master since 2 months...
