### ISSUE TITLE
add option `waitFinishWritten` to ensure emit change event(or finish event) after some big file written done to disk

### ISSUE THREAD

**Issue by lovetingyuan** [webpack/watchpack#99]
sometimes, when change event is emitted, I can not read the final content of watched files(it's size is big)
like 'chokidar', it offers a option: `awaitWriteFinish`

**Comment by evilebottnawi** [comment]
@lovetingyuan please create minimum reproducible test repo

**Comment by lovetingyuan** [comment]
here is the repo: https://github.com/lovetingyuan/watchpack-bug-reproduce
thanks!

**Comment by evilebottnawi** [comment]
Looks like a bug we need fix it

**Comment by evilebottnawi** [comment]
@lovetingyuan Original file have length `541251`, but you check `assert.ok(fileContent.trim().length > 555555)`, it is always will be failed

**Comment by lovetingyuan** [comment]
![2019-02-21_191220](https://user-images.githubusercontent.com/7310471/53165145-e91cd880-360c-11e9-97da-bdfa5ae0a06b.png)
the length is larger than `555555` @evilebottnawi

**Comment by evilebottnawi** [comment]
@loveky no:
```
total 556
-rw-r--r-- 1 evilebottnawi evilebottnawi    435 фев 21 13:57 index.js
drwxr-xr-x 5 evilebottnawi evilebottnawi   4096 фев 21 13:51 node_modules
-rw-r--r-- 1 evilebottnawi evilebottnawi    308 фев 21 13:51 package.json
-rw-r--r-- 1 evilebottnawi evilebottnawi    911 фев 21 13:51 package-lock.json
-rw-r--r-- 1 evilebottnawi evilebottnawi    227 фев 21 13:48 README.md
-rw-r--r-- 1 evilebottnawi evilebottnawi 541251 фев 21 13:53 test.txt
-rw-r--r-- 1 evilebottnawi evilebottnawi    335 фев 21 13:49 watchpack-bug-reproduce.iml
```

**Comment by evilebottnawi** [comment]
What is you filesystem?

**Comment by lovetingyuan** [comment]
sorry, I use windows, but error still occurs even the size was changed to `500000`
I update the repo and read the file size at first used as the compared size number.
By the way, I found that the first time modification will not cause error(or in most cases, not sure), but when I modify `test.txt` again, error is there
@evilebottnawi

**Comment by evilebottnawi** [comment]
@lovetingyuan Something wrong with you fs, can't reproducible on linux (Ubuntu), windows 10, macos

**Comment by evilebottnawi** [comment]
Please provide information about your os, fs where you store repo, any additional information what can help to find problem

**Comment by lovetingyuan** [comment]
my envrionment info:
editor: vscode
* version: 1.31.1 (system setup)
* commit: 1b8e8302e405050205e69b59abb3559592bb9e60
* date: 2019-02-12T02:20:54.427Z
* Electron: 3.1.2
* Chrome: 66.0.3359.181
* Node.js: 10.2.0
* V8: 6.6.346.32
* OS: Windows_NT x64 10.0.17134

I test it on macos, no error(both vscode and vim).
On windows, If I use vscode(or vim), there are errors, because the `change` event was emitted many times during one modification.
while, if I use notepad(or gedit)(system simple default editor), everything is ok.
I am not sure whether it is a problem of editor or os.
If you can not reproduce this issue, feel free to close it😊. Thanks.

**Comment by evilebottnawi** [comment]
@lovetingyuan i think problem on IDE side, can't reproduce on difference os with difference editors
